[db]
  data-source = "mongodb+srv://dhimanrajat:Y8IAGI0lVrMhjvkU@cluster0.mytkgu6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  prepare-stmt = true
  log-level = 1
  [db.pool]
    enable = true
    max-idle-connections = 25
    max-lifetime = "10m"
    max-open-connections = 25

[cronjobs]
  enable = true

[jwt]
  allowed-users = [""]
  secret = "f498050fbf53a8e3e4e54e933e544dceea27280d18963e1c9bd526a0443a0f12f7cabaad4868e5cc12cf0788e4de93bbc34f712f3b8b3ca6b898d3aca1fff2b0"
  session-time = "30d"

[log]
  development = true
  level = -1

[server]
  graceful-shutdown = "15s"
  port = 8080
  read-timeout = "1h"
  write-timeout = "1h"

[tg]
  app-hash = "e469e84c943ce3b8b056eb6a296f2c67"
  app-id = 21857983
  app-version = "4.6.3 K"
  bg-bots-limit = 5
  device-model = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0"
  disable-stream-bots = false
  lang-code = "en"
  lang-pack = "webk"
  rate = 100
  rate-burst = 5
  rate-limit = true
  session-file = ""
  system-lang-code = "en-US"
  system-version = "Win32"
  proxy= "http://127.0.0.1:8080"
  
  [tg.uploads]
    encryption-key = ""
    retention = "7d"
    threads = 8
  [tg.stream]
    multi-threads = 0
    buffers = 8

